
class PersistencePrompt():
    GOAL = """You are tasked with identifying activity by a potential attacker that sets up (i.e. creates) persistence on the system, that is, actions that allow an adversary to maintain access to the system across restarts, changed credentials, and other interruptions that could cut off their access. 
An example of action used to create persistence involves the adversary changing configurations that can let them maintain foothold on the system. Another example of creation of persistence is an adversary replacing or hijacking legitimate code or adding a startup code.

If the activity sets up a well documented persistence technique, report them. Do not report the activities that do not show creation/setting-up of persistence, for example, activities that just show execution (without creation) of potential persistence actions.

You must identify all specific actions that may be used for creation of persistence, and assess how suspicious each action is, i.e., likely to be caused by an attacker."""

    OUTPUT_FORMAT = [
        ("key log lines", "str", "list of comma separated log lines showing the creation of {task}."),
        ("timestamp", "str", "timestamp of the log record demonstrating creation of {task}."),
        ("pid", "int", "pid of the process that creates {task}."),
        ("evidence for", "str", "describe all the evidence from the key log lines that indicates the creation of suspicious {task}."),
        ("evidence against", "str", "describe all the evidence from the key log lines that indicates either not suspicious or not creation of {task}."),
        ("deliberation", "str", "analyze the evidence above, taking into account evidence for and against, in order to reach a conclusion."),
        ("verdict", "str", "one of ['LOW_SUSPICIOUS', 'MEDIUM_SUSPICIOUS', 'HIGH_SUSPICIOUS']. Use 'HIGH_SUSPICIOUS' only when the identified behavior is highly likely for an attacker to create malicious {task}. Use 'MEDIUM_SUSPICIOUS' when it is not clear how feasible it would be for an attacker to abuse. Use 'LOW_SUSPICIOUS' when the activity is likely benign, part of regular system activity, or generally difficult for the attacker to use as {task}."),
    ]

    OUTPUT_FORMAT_MITRE = [("MITRE technique", "str", "one of the 20 MITRE ATT&CK {task} techniques. See below."),]#re-count the number MITRE ATT&CK techniques for other security tasks

    OUTPUT_DESCRIPTION = """One JSON object for each distinct persistence instance."""

    ADDITIONAL_SECTION = """## MITRE ATT&CK {task} Reference
1. 'Account Manipulation': manipulate accounts to maintain and/or elevate access to victim systems, including actions that preserves or modifies adversary access to a compromised account, such as modifying credentials or permission groups. 2. 'BITS Jobs': abuse BITS (Windows Background Intelligent Transfer Service) jobs to persistently execute code and perform various background tasks. 3. 'Boot or Logon Autostart Execution': configure system settings to automatically execute a program during system boot or logon to maintain persistence or gain higher-level privileges on compromised systems. 4. 'Boot or Logon Initialization Scripts': use scripts automatically executed at boot or logon initialization to establish persistence. 5. 'Browser Extensions': abuse Internet browser extensions to establish persistent access to victim systems. 6. 'Compromise Host Software Binary': modify host software binaries to establish persistent access to systems. 7. 'Create Account': create an account to maintain access to victim systems. 8. 'Create or Modify System Process': create or modify system-level processes to repeatedly execute malicious payloads as part of persistence. 9. 'Event Triggered Execution': establish persistence and/or elevate privileges using system mechanisms that trigger execution based on specific events. 10. 'External Remote Services': leverage external-facing remote services (such as VPNs, Citrix, Windows Remote Management, VNC) to persist within a network. 11. 'Hijack Execution Flow': hijacking the way operating systems run programs. 12. 'Implant Internal Image': implant cloud or container images with malicious code to establish persistence after gaining access to an environment. 13. 'Modify Authentication Process': modify authentication mechanisms and processes to access user credentials or enable otherwise unwarranted access to accounts. 14. 'Office Application Startup': leverage Microsoft Office-based applications for persistence between startups. 15. 'Power Settings': impair a system's ability to hibernate, reboot, or shut down in order to extend access to infected machines. 16. 'Pre-OS Boot': abuse Pre-OS Boot mechanisms as a way to establish persistence on a system. 17. 'Scheduled Task/Job': abuse task scheduling functionality to facilitate initial or recurring execution of malicious code. 18. 'Server Software Component': abuse legitimate extensible development features of servers to establish persistent access to systems. 19. 'Traffic Signaling': use traffic signaling to hide open ports or other malicious functionality used for persistence or command and control. Traffic signaling involves the use of a magic value or sequence that must be sent to a system to trigger a special response, such as opening a closed port or executing a malicious task. 20. 'Valid Accounts': defined as activity to obtain and abuse credentials of existing accounts."""
