import re
import ast
import logging
import sys
from collections import deque, defaultdict, Counter
from parser.customparser import Parser

logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    stream=sys.stdout
)


class ParserLateralMovement(Parser):

    def __init__(self, dataset, task, parser_version="legacy"):
        super().__init__(dataset, task)
        # v1 has only the legacy queue-based parser; arg accepted for API parity with v2.
        self.parser_version = parser_version
        self.format_err_count = defaultdict(int)


    def process_llm_lateralmovement_outputs(self, ts_line, external_host_line, pid_line, username_line, key_log_line_line, mitre_technique_line, explanation_line):
        external_host = None
        username = None
        key_log_line = None

        gtfriendly_timestamp = self.process_timestamp(ts_line)

        if external_host_line:
            if external_host_line[-1] == ",":
                external_host_line = external_host_line[:-1]
            external_host_line = "{" + external_host_line + "}"
            try:
                external_host_dict = ast.literal_eval(external_host_line)
                key = list(external_host_dict.keys())[0]
                assert key == "external host" or "external_host", "key is not equal to 'external host'"
                external_host = list(external_host_dict.values())[0]
            except:
                external_host = "Couldn't parse external host"

        pid = self.process_pid(pid_line)

        if username_line:
            if username_line[-1] == ",":
                username_line = username_line[:-1]
            username_line = username_line.split(":")
            key = username_line[0].strip().strip('"')
            val = username_line[1].strip().strip('"')
            assert key == "username", "key is not equal to 'username'"
            username = val
            username = username.replace(r"\\\\", "\\")
            username = username.replace(r"\\", "\\")

        if key_log_line_line:
            if key_log_line_line[-1] == ",":
                key_log_line_line = key_log_line_line[:-1]
            key_log_line_line = "{" + key_log_line_line + "}"
            try:
                key_log_line_dict = ast.literal_eval(key_log_line_line)
                key = list(key_log_line_dict.keys())[0]
                assert key == "key log line" or "key_log_line", "key is not equal to 'key log line'"
                key_log_line = list(key_log_line_dict.values())[0]
            except:
                key_log_line = "Couldn't parse the key log line"
            key_log_line = key_log_line.replace(r"\\\\", "\\")
            key_log_line = key_log_line.replace(r"\\", "\\")

        explanation = self.process_explanation(explanation_line)

        mitre_technique = self.process_mitretechnique(mitre_technique_line)

        return gtfriendly_timestamp, external_host, pid, username, key_log_line, mitre_technique, explanation

    def parse_lateralmovement_llmoutput(self, out_fpath):

        assert "_v14" in out_fpath, "this parser is for the output generated by lateral movement prompt labelled by key v14"

        logging.info("Parsing file (legacy parser): %s", out_fpath)

        FIELD_KEYS = ('"timestamp"', '"external host"', '"external_host"', '"pid"', '"username"', '"key log line"', '"MITRE technique"', '"explanation"')

        """
        This dictionary stores lists of LLM inference outputs per round. It contains only the chunks that generate
        non empty outputs
        Key: chunk identifier - 3 tuple (start lno. of chunk, max. number of lines in chunk, timestamp of start lno.)
        Value: a dictionary whose key is the round number and value is list of tuples. Each tuple contains the important attributes generated by LLM such as round number, timestamp, hostname, key log lines, explanation, etc.
        """
        llmresponse_dict = defaultdict(dict)

        llmoutput_chunk_key = (None, None, None)
        q = deque()

        """ This dictionary essentially saves the number of rounds per chunk """
        jsonobjectcnt_per_chunk = defaultdict(int)

        num_rounds = 0
        something_wrong = False
        with open(out_fpath, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith("****Starting line num: "):
                    pattern = r"\*\*\*\*Starting line num: (\d+). Num lines: (\d+). (.*)\*\*\*\*"
                    match = re.search(pattern, line)
                    lnum = int(match.group(1))
                    numlines = int(match.group(2))
                    time = match.group(3)
                    llmoutput_chunk_key = (lnum, numlines, time)
                    jsonobjectcnt_per_chunk[llmoutput_chunk_key] += 1
                    current_rdnum = jsonobjectcnt_per_chunk[llmoutput_chunk_key]
                    llmresponse_dict[llmoutput_chunk_key][current_rdnum] = []

                if "\"timestamp\"" in line:
                    q.append(line)
                    continue

                if len(q) >= 1 and len(q) < 7:
                    if not any(line.strip().startswith(k) for k in FIELD_KEYS):
                        continue
                    q.appendleft(line)
                    if len(q) == 2 and not ('\"external host\"' in line or '\"external_host\"' in line):
                        something_wrong = True
                        print("external host is wrong")
                        self.format_err_count["external host"] += 1
                    if len(q) == 3 and '\"pid\"' not in line:
                        something_wrong = True
                        print("pid is wrong")
                        self.format_err_count["pid"] += 1
                    if len(q) == 4 and '\"username\"' not in line:
                        something_wrong = True
                        print("username is wrong")
                        self.format_err_count["username"] += 1
                    if len(q) == 5 and '\"key log line\"' not in line:
                        something_wrong = True
                        print("key log line is wrong")
                        self.format_err_count["key log line"] += 1
                    if len(q) == 6 and '\"MITRE technique\"' not in line:
                        something_wrong = True
                        print("MITRE technique is wrong")
                        self.format_err_count["MITRE technique"] += 1
                    if len(q) == 7 and '\"explanation\"' not in line:
                        something_wrong = True
                        print("explanation is wrong")
                        self.format_err_count["explanation"] += 1


                    if something_wrong:
                        print("Found format following error in LLM output!!")
                        ts_line = None
                        external_host_line = None
                        pid_line = None
                        username_line = None
                        key_log_line_line = None
                        mitre_technique_line = None
                        explanation_line = None

                        poplast = False
                        while q:
                            if poplast == False:
                                q.popleft()
                                poplast = True
                            if len(q) == 7 and poplast:
                                explanation_line = q.popleft()
                            if len(q) == 6 and poplast:
                                mitre_technique_line = q.popleft()
                            if len(q) == 5 and poplast:
                                key_log_line_line = q.popleft()
                            if len(q) == 4 and poplast:
                                username_line = q.popleft()
                            if len(q) == 3 and poplast:
                                pid_line = q.popleft()
                            if len(q) == 2 and poplast:
                                external_host_line = q.popleft()
                            if len(q) == 1 and poplast:
                                ts_line = q.popleft()

                        try:
                            gtfriendly_timestamp, external_host, pid, username, key_log_line, mitre_technique, explanation = self.process_llm_lateralmovement_outputs(ts_line, external_host_line, pid_line, username_line, key_log_line_line, mitre_technique_line, explanation_line)

                            if gtfriendly_timestamp != None and external_host != None:
                                llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, external_host, pid, username, key_log_line, mitre_technique, explanation)))
                        except Exception as e:
                            logging.info("Incomplete/unparseable LLM output in error-recovery path for chunk %s, round %s: %s — ignoring block", llmoutput_chunk_key, current_rdnum, e)
                            self.format_err_count["incomplete_output"] += 1

                    something_wrong = False

                if len(q) == 7:
                    ts_line = q.pop()
                    external_host_line = q.pop()
                    pid_line = q.pop()
                    username_line = q.pop()
                    key_log_line_line = q.pop()
                    mitre_technique_line = q.pop()
                    explanation_line = q.pop()

                    assert len(q) == 0, print("Did not completely empty the queue")

                    try:
                        gtfriendly_timestamp, external_host, pid, username, key_log_line, mitre_technique, explanation = self.process_llm_lateralmovement_outputs(ts_line, external_host_line, pid_line, username_line, key_log_line_line, mitre_technique_line, explanation_line)

                        # llmresponse_dict[k].append(tuple((jsonobjectcnt_per_chunk[k], timestamp, external_host, method, username, evidence)))
                        llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, external_host, pid, username, key_log_line, mitre_technique, explanation)))
                    except Exception as e:
                        logging.info("Incomplete/unparseable LLM output in normal path for chunk %s, round %s: %s — ignoring block", llmoutput_chunk_key, current_rdnum, e)
                        self.format_err_count["incomplete_output"] += 1

        # Handle partial queue left at end of file (incomplete JSON object)
        if len(q) > 0:
            logging.info("Partial queue (%d items) at end of file for chunk %s, round %s — ignoring incomplete block", len(q), llmoutput_chunk_key, current_rdnum)
            self.format_err_count["incomplete_output"] += 1
            q.clear()

        for k,v in jsonobjectcnt_per_chunk.items():
            num_rounds = max(num_rounds, v)

        return llmresponse_dict, num_rounds
