import re
import ast
import logging
import sys
from collections import deque, defaultdict, Counter
from parser.customparser import Parser, has_prompt_version_label
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    stream=sys.stdout
)


class ParserLateralMovement(Parser):
    
    def __init__(self, dataset, task):
        super().__init__(dataset, task)
        self.format_err_count = defaultdict(int)

    
    def process_llm_lateralmovement_outputs(self, ts_line, external_host_line, pid_line, username_line, key_log_line_line, evidencefor_line, evidenceagainst_line, deliberation_line, verdict_line):
        external_host = None
        username = None
        key_log_line = None
        
        gtfriendly_timestamp = self.process_timestamp(ts_line)

        if external_host_line:
            if external_host_line[-1] == ",":
                external_host_line = external_host_line[:-1]
            external_host_line = "{" + external_host_line + "}"
            try:
                external_host_dict = ast.literal_eval(external_host_line)
                key = list(external_host_dict.keys())[0]
                assert key == "external host" or "external_host", "key is not equal to 'external host'"
                external_host = list(external_host_dict.values())[0]
            except:
                external_host = "Couldn't parse external host"

        pid = self.process_pid(pid_line)

        if username_line:
            if username_line[-1] == ",":
                username_line = username_line[:-1]
            username_line = username_line.split(":")
            key = username_line[0].strip().strip('"')
            val = username_line[1].strip().strip('"')
            assert key == "username", "key is not equal to 'username'"
            username = val
            username = username.replace(r"\\\\", "\\")
            username = username.replace(r"\\", "\\")
        
        if key_log_line_line:
            if key_log_line_line[-1] == ",":
                key_log_line_line = key_log_line_line[:-1]
            key_log_line_line = "{" + key_log_line_line + "}"
            try:
                key_log_line_dict = ast.literal_eval(key_log_line_line)
                key = list(key_log_line_dict.keys())[0]
                assert key == "key log line" or "key_log_line", "key is not equal to 'key log line'"
                key_log_line = list(key_log_line_dict.values())[0]
            except:
                key_log_line = "Couldn't parse the key log line"
            key_log_line = key_log_line.replace(r"\\\\", "\\")
            key_log_line = key_log_line.replace(r"\\", "\\")

        evidence_for = self.process_evidencefor(evidencefor_line)
        evidence_against = self.process_evidenceagainst(evidenceagainst_line)
        deliberation = self.process_deliberation(deliberation_line)
        verdict = self.process_verdict(verdict_line)
        
        return gtfriendly_timestamp, external_host, pid, username, key_log_line,evidence_for, evidence_against, deliberation, verdict

    def parse_lateralmovement_llmoutput(self, out_fpath):

        # assert "_v18_" in out_fpath, "this parser is for the output generated by lateral movement prompt labelled by key v18"
        assert has_prompt_version_label(out_fpath, "v2"), "this parser is for the output generated by lateral movement prompt labelled by key v2"

        print(f"Parsing file: {out_fpath}")

        """
        This dictionary stores lists of LLM inference outputs per round. It contains only the chunks that generate
        non empty outputs
        Key: chunk identifier - 3 tuple (start lno. of chunk, max. number of lines in chunk, timestamp of start lno.)
        Value: a dictionary whose key is the round number and value is list of tuples. Each tuple contains the important attributes generated by LLM such as round number, timestamp, hostname, key log lines, explanation, etc.
        """
        llmresponse_dict = defaultdict(dict)
        
        llmoutput_chunk_key = (None, None, None)
        q = deque()

        """ This dictionary essentially saves the number of rounds per chunk """
        jsonobjectcnt_per_chunk = defaultdict(int)
        
        num_rounds = 0
        something_wrong = False
        with open(out_fpath, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith("****Starting line num: "):
                    pattern = r"\*\*\*\*Starting line num: (\d+). Num lines: (\d+). (.*)\*\*\*\*"
                    match = re.search(pattern, line)
                    lnum = int(match.group(1))
                    numlines = int(match.group(2))
                    time = match.group(3)
                    llmoutput_chunk_key = (lnum, numlines, time)
                    jsonobjectcnt_per_chunk[llmoutput_chunk_key] += 1
                    current_rdnum = jsonobjectcnt_per_chunk[llmoutput_chunk_key]
                    llmresponse_dict[llmoutput_chunk_key][current_rdnum] = []
                
                #change the sequence of timestamp and key log line
                if "\"key log line\"" in line:
                    q.append(line)
                    continue

                if len(q) >= 1 and len(q) < 9:
                    q.appendleft(line)
                    if len(q) == 2 and '\"timestamp\"' not in line:
                        something_wrong = True
                        print("timestamp is wrong")
                        self.format_err_count["timestamp"] += 1
                    if len(q) == 3 and not ('\"external host\"' in line or '\"external_host\"' in line):
                        something_wrong = True
                        print("external host is wrong")
                        self.format_err_count["external host"] += 1
                    if len(q) == 4 and '\"pid\"' not in line:
                        something_wrong = True
                        print("pid is wrong")
                        self.format_err_count["pid"] += 1
                    if len(q) == 5 and '\"username\"' not in line:
                        something_wrong = True
                        print("username is wrong")
                        self.format_err_count["username"] += 1
                    if len(q) == 6 and '\"evidence for\"' not in line:
                        something_wrong = True
                        print("evidence for is wrong")
                        self.format_err_count["evidence for"] += 1
                    if len(q) == 7 and '\"evidence against\"' not in line:
                        something_wrong = True
                        print("evidence against is wrong")
                        self.format_err_count["evidence against"] += 1
                    if len(q) == 8 and '\"deliberation\"' not in line:
                        something_wrong = True
                        print("deliberation is wrong")
                        self.format_err_count["deliberation"] += 1
                    if len(q) == 9 and '\"verdict\"' not in line:
                        something_wrong = True
                        print("verdict is wrong")
                        self.format_err_count["verdict"] += 1


                    if something_wrong:
                        print("Found format following error in LLM output!!")
                        ts_line = None
                        external_host_line = None
                        pid_line = None
                        username_line = None
                        key_log_line_line = None
                        evidencefor_line = None
                        evidenceagainst_line = None
                        deliberation_line = None
                        verdict_line = None

                        poplast = False
                        while q:
                            if poplast == False:
                                q.popleft()
                                poplast = True
                            if len(q) == 9 and poplast:
                                verdict_line = q.popleft()
                            if len(q) == 8 and poplast:
                                deliberation_line = q.popleft()
                            if len(q) == 7 and poplast:
                                evidenceagainst_line = q.popleft()
                            if len(q) == 6 and poplast:
                                evidencefor_line = q.popleft()
                            if len(q) == 5 and poplast:
                                username_line = q.popleft()
                            if len(q) == 4 and poplast:
                                pid_line = q.popleft()
                            if len(q) == 3 and poplast:
                                external_host_line = q.popleft()
                            if len(q) == 2 and poplast:
                                ts_line = q.popleft()
                            if len(q) == 1 and poplast:
                                key_log_line_line = q.popleft()

                        gtfriendly_timestamp, external_host, pid, username, key_log_line, evidencefor, evidenceagainst, deliberation, verdict = self.process_llm_lateralmovement_outputs(ts_line, external_host_line, pid_line, username_line, key_log_line_line, evidencefor_line, evidenceagainst_line, deliberation_line, verdict_line)

                        if gtfriendly_timestamp != None and external_host != None:
                            llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, external_host, pid, username, key_log_line, evidencefor, evidenceagainst, deliberation, verdict)))

                    something_wrong = False

                if len(q) == 9:
                    key_log_line_line = q.pop()
                    ts_line = q.pop()
                    external_host_line = q.pop()
                    pid_line = q.pop()
                    username_line = q.pop()
                    evidencefor_line = q.pop()
                    evidenceagainst_line = q.pop()
                    deliberation_line = q.pop()
                    verdict_line = q.pop()

                    assert len(q) == 0, print("Did not completely empty the queue")

                    gtfriendly_timestamp, external_host, pid, username, key_log_line, evidencefor, evidenceagainst, deliberation, verdict = self.process_llm_lateralmovement_outputs(ts_line, external_host_line, pid_line, username_line, key_log_line_line, evidencefor_line, evidenceagainst_line, deliberation_line, verdict_line)

                    # llmresponse_dict[k].append(tuple((jsonobjectcnt_per_chunk[k], timestamp, external_host, method, username, evidence)))
                    llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, external_host, pid, username, key_log_line, evidencefor, evidenceagainst, deliberation, verdict)))

        for k,v in jsonobjectcnt_per_chunk.items():
            num_rounds = max(num_rounds, v)
        
        return llmresponse_dict, num_rounds