import re
import ast
import logging
import sys
from collections import deque, defaultdict
from parser.customparser import Parser

logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    stream=sys.stdout
)


class ParserExfiltration(Parser):

    def __init__(self, dataset, task, parser_version="legacy"):
        super().__init__(dataset, task)
        # v1 has only the legacy queue-based parser; arg accepted for API parity with v2.
        self.parser_version = parser_version
        self.format_err_count = defaultdict(int)


    def process_llm_exfiltration_outputs(self, ts_line, exfiltrated_data_line, pid_line, key_log_lines_line, explanation_line):
        exfiltrated_data = None
        key_log_lines = None
        explanation = None

        gtfriendly_timestamp = self.process_timestamp(ts_line)

        if exfiltrated_data_line:
            if exfiltrated_data_line[-1] == ",":
                exfiltrated_data_line = exfiltrated_data_line[:-1]
            exfiltrated_data_line = "{" + exfiltrated_data_line + "}"
            try:
                exfiltrated_data_dict = ast.literal_eval(exfiltrated_data_line)
                key = list(exfiltrated_data_dict.keys())[0]
                assert key == "exfiltrated data", "key is not equal to 'exfiltrated data'"
                exfiltrated_data = list(exfiltrated_data_dict.values())[0]
            except:
                exfiltrated_data = "Couldn't parse exfiltrated data"

        pid = self.process_pid(pid_line)

        if key_log_lines_line:
            if key_log_lines_line[-1] == ",":
                key_log_lines_line = key_log_lines_line[:-1]
            key_log_lines_line = "{" + key_log_lines_line + "}"
            try:
                key_log_lines_dict = ast.literal_eval(key_log_lines_line)
                key = list(key_log_lines_dict.keys())[0]
                assert key == "key log lines" or "key_log_lines", "key is not equal to 'key log line'"
                key_log_lines = list(key_log_lines_dict.values())[0]
            except:
                key_log_lines = "Couldn't parse the key log line"
            key_log_lines = key_log_lines.replace(r"\\\\", "\\")
            key_log_lines = key_log_lines.replace(r"\\", "\\")

        explanation = self.process_explanation(explanation_line)

        return gtfriendly_timestamp, exfiltrated_data, pid, key_log_lines, explanation

    def parse_exfiltration_llmoutput(self, out_fpath):

        assert "_v15" in out_fpath, "this parser is for the output generated by exfiltration prompt labelled by key v15"

        logging.info("Parsing file (legacy parser): %s", out_fpath)

        FIELD_KEYS = ('"timestamp"', '"pid"', '"exfiltrated data"', '"key log lines"', '"explanation"')

        """
        This dictionary stores lists of LLM inference outputs per round. It contains only the chunks that generate
        non empty outputs
        Key: chunk identifier - 3 tuple (start lno. of chunk, max. number of lines in chunk, timestamp of start lno.)
        Value: a dictionary whose key is the round number and value is list of tuples. Each tuple contains the important attributes generated by LLM such as round number, timestamp, hostname, key log lines, explanation, etc.
        """
        llmresponse_dict = defaultdict(dict)

        llmoutput_chunk_key = (None, None, None)
        q = deque()

        """ This dictionary essentially saves the number of rounds per chunk """
        jsonobjectcnt_per_chunk = defaultdict(int)

        num_rounds = 0
        something_wrong = False
        with open(out_fpath, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith("****Starting line num: "):
                    pattern = r"\*\*\*\*Starting line num: (\d+). Num lines: (\d+). (.*)\*\*\*\*"
                    match = re.search(pattern, line)
                    lnum = int(match.group(1))
                    numlines = int(match.group(2))
                    time = match.group(3)
                    llmoutput_chunk_key = (lnum, numlines, time)
                    jsonobjectcnt_per_chunk[llmoutput_chunk_key] += 1
                    current_rdnum = jsonobjectcnt_per_chunk[llmoutput_chunk_key]
                    llmresponse_dict[llmoutput_chunk_key][current_rdnum] = []

                #change the sequence of timestamp and key log line
                if "\"timestamp\"" in line:
                    q.append(line)
                    continue

                if len(q) >= 1 and len(q) < 5:
                    if not any(line.strip().startswith(k) for k in FIELD_KEYS):
                        continue
                    q.appendleft(line)
                    if len(q) == 2 and '\"pid\"' not in line:
                        something_wrong = True
                        print("pid is wrong")
                        self.format_err_count["pid"] += 1
                    if len(q) == 3 and '\"exfiltrated data\"' not in line:
                        something_wrong = True
                        print("exfiltrated data is wrong")
                        self.format_err_count["exfiltrated data"] += 1
                    if len(q) == 4 and '\"key log lines\"' not in line:
                        something_wrong = True
                        print("key log lines is wrong")
                        self.format_err_count["key log lines"] += 1
                    if len(q) == 5 and '\"explanation\"' not in line:
                        something_wrong = True
                        print("explanation is wrong")
                        self.format_err_count["explanation"] += 1


                    if something_wrong:
                        print("Found format following error in LLM output!!")
                        key_log_lines_line = None
                        ts_line = None
                        pid_line = None
                        exfiltrated_data_line = None
                        explanation_line = None

                        poplast = False
                        while q:
                            if poplast == False:
                                q.popleft()
                                poplast = True
                            if len(q) == 5 and poplast:
                                explanation_line = q.popleft()
                            if len(q) == 4 and poplast:
                                key_log_lines_line = q.popleft()
                            if len(q) == 3 and poplast:
                                exfiltrated_data_line = q.popleft()
                            if len(q) == 2 and poplast:
                                pid_line = q.popleft()
                            if len(q) == 1 and poplast:
                                ts_line = q.popleft()

                        try:
                            gtfriendly_timestamp, exfiltrated_data, pid, key_log_lines, explanation = self.process_llm_exfiltration_outputs(ts_line, exfiltrated_data_line, pid_line, key_log_lines_line, explanation_line)

                            if gtfriendly_timestamp != None and exfiltrated_data != None:
                                llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, exfiltrated_data, pid, key_log_lines, explanation)))
                        except Exception as e:
                            logging.info("Incomplete/unparseable LLM output in error-recovery path for chunk %s, round %s: %s — ignoring block", llmoutput_chunk_key, current_rdnum, e)
                            self.format_err_count["incomplete_output"] += 1

                    something_wrong = False

                if len(q) == 5:
                    ts_line = q.pop()
                    pid_line = q.pop()
                    exfiltrated_data_line = q.pop()
                    key_log_lines_line = q.pop()
                    explanation_line = q.pop()

                    assert len(q) == 0, print("Did not completely empty the queue")

                    try:
                        gtfriendly_timestamp, exfiltrated_data, pid, key_log_lines, explanation = self.process_llm_exfiltration_outputs(ts_line, exfiltrated_data_line, pid_line, key_log_lines_line, explanation_line)

                        # llmresponse_dict[k].append(tuple((jsonobjectcnt_per_chunk[k], timestamp, external_host, method, username, evidence)))
                        llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, exfiltrated_data, pid, key_log_lines, explanation)))
                    except Exception as e:
                        logging.info("Incomplete/unparseable LLM output in normal path for chunk %s, round %s: %s — ignoring block", llmoutput_chunk_key, current_rdnum, e)
                        self.format_err_count["incomplete_output"] += 1

        # Handle partial queue left at end of file (incomplete JSON object)
        if len(q) > 0:
            logging.info("Partial queue (%d items) at end of file for chunk %s, round %s — ignoring incomplete block", len(q), llmoutput_chunk_key, current_rdnum)
            self.format_err_count["incomplete_output"] += 1
            q.clear()

        for k,v in jsonobjectcnt_per_chunk.items():
            num_rounds = max(num_rounds, v)

        return llmresponse_dict, num_rounds
