import re
import ast
from collections import deque, defaultdict, Counter
from parser.customparser import Parser, has_prompt_version_label


class ParserExfiltration(Parser):
    
    def __init__(self, dataset, task):
        super().__init__(dataset, task)
        self.format_err_count = defaultdict(int)

    
    def process_llm_exfiltration_outputs(self, ts_line, exfiltrated_data_line, pid_line, exfiltration_method_line, key_log_lines_line, evidencefor_line, evidenceagainst_line, deliberation_line, verdict_line):
        exfiltrated_data = None
        key_log_lines = None
        exfiltration_method = None
        
        gtfriendly_timestamp = self.process_timestamp(ts_line)

        if exfiltrated_data_line:
            if exfiltrated_data_line[-1] == ",":
                exfiltrated_data_line = exfiltrated_data_line[:-1]
            exfiltrated_data_line = "{" + exfiltrated_data_line + "}"
            try:
                exfiltrated_data_dict = ast.literal_eval(exfiltrated_data_line)
                key = list(exfiltrated_data_dict.keys())[0]
                assert key == "exfiltrated data", "key is not equal to 'exfiltrated data'"
                exfiltrated_data = list(exfiltrated_data_dict.values())[0]
            except:
                exfiltrated_data = "Couldn't parse exfiltrated data"

        pid = self.process_pid(pid_line)

        if exfiltration_method_line:
            if exfiltration_method_line[-1] == ",":
                exfiltration_method_line = exfiltration_method_line[:-1]
            exfiltration_method_line = "{" + exfiltration_method_line + "}"
            try:
                exfiltration_method_dict = ast.literal_eval(exfiltration_method_line)
                key = list(exfiltration_method_dict.keys())[0]
                assert key == "exfiltration method", "key is not equal to 'exfiltration method'"
                exfiltration_method = list(exfiltration_method_dict.values())[0]
            except:
                exfiltration_method = "Couldn't parse exfiltration method"
        
        if key_log_lines_line:
            if key_log_lines_line[-1] == ",":
                key_log_lines_line = key_log_lines_line[:-1]
            key_log_lines_line = "{" + key_log_lines_line + "}"
            try:
                key_log_lines_dict = ast.literal_eval(key_log_lines_line)
                key = list(key_log_lines_dict.keys())[0]
                assert key == "key log lines" or "key_log_lines", "key is not equal to 'key log line'"
                key_log_lines = list(key_log_lines_dict.values())[0]
            except:
                key_log_lines = "Couldn't parse the key log line"
            key_log_lines = key_log_lines.replace(r"\\\\", "\\")
            key_log_lines = key_log_lines.replace(r"\\", "\\")

        evidence_for = self.process_evidencefor(evidencefor_line)
        evidence_against = self.process_evidenceagainst(evidenceagainst_line)
        deliberation = self.process_deliberation(deliberation_line)
        verdict = self.process_verdict(verdict_line)
        
        return gtfriendly_timestamp, exfiltrated_data, pid, exfiltration_method, key_log_lines, evidence_for, evidence_against, deliberation, verdict

    def parse_exfiltration_llmoutput(self, out_fpath):

        # assert "_v18_" in out_fpath, "this parser is for the output generated by exfiltration prompt labelled by key v18"
        assert has_prompt_version_label(out_fpath, "v2"), "this parser is for the output generated by exfiltration prompt labelled by key v2"

        print(f"Parsing file: {out_fpath}")

        """
        This dictionary stores lists of LLM inference outputs per round. It contains only the chunks that generate
        non empty outputs
        Key: chunk identifier - 3 tuple (start lno. of chunk, max. number of lines in chunk, timestamp of start lno.)
        Value: a dictionary whose key is the round number and value is list of tuples. Each tuple contains the important attributes generated by LLM such as round number, timestamp, hostname, key log lines, explanation, etc.
        """
        llmresponse_dict = defaultdict(dict)
        
        llmoutput_chunk_key = (None, None, None)
        q = deque()

        """ This dictionary essentially saves the number of rounds per chunk """
        jsonobjectcnt_per_chunk = defaultdict(int)
        
        num_rounds = 0
        something_wrong = False
        with open(out_fpath, 'r') as f:
            for line in f:
                line = line.strip()
                if line.startswith("****Starting line num: "):
                    pattern = r"\*\*\*\*Starting line num: (\d+). Num lines: (\d+). (.*)\*\*\*\*"
                    match = re.search(pattern, line)
                    lnum = int(match.group(1))
                    numlines = int(match.group(2))
                    time = match.group(3)
                    llmoutput_chunk_key = (lnum, numlines, time)
                    jsonobjectcnt_per_chunk[llmoutput_chunk_key] += 1
                    current_rdnum = jsonobjectcnt_per_chunk[llmoutput_chunk_key]
                    llmresponse_dict[llmoutput_chunk_key][current_rdnum] = []
                
                #change the sequence of timestamp and key log line
                if "\"key log lines\"" in line:
                    q.append(line)
                    continue

                if len(q) >= 1 and len(q) < 9:
                    q.appendleft(line)
                    if len(q) == 2 and '\"timestamp\"' not in line:
                        something_wrong = True
                        print("timestamp is wrong")
                        self.format_err_count["timestamp"] += 1
                    if len(q) == 3 and '\"pid\"' not in line:
                        something_wrong = True
                        print("pid is wrong")
                        self.format_err_count["pid"] += 1
                    if len(q) == 4 and '\"exfiltration method\"' not in line:
                        something_wrong = True
                        print("exfiltration method is wrong")
                        self.format_err_count["exfiltration method"] += 1
                    if len(q) == 5 and '\"exfiltrated data\"' not in line:
                        something_wrong = True
                        print("exfiltrated data is wrong")
                        self.format_err_count["exfiltrated data"] += 1
                    if len(q) == 6 and '\"evidence for\"' not in line:
                        something_wrong = True
                        print("evidence for is wrong")
                        self.format_err_count["evidence for"] += 1
                    if len(q) == 7 and '\"evidence against\"' not in line:
                        something_wrong = True
                        print("evidence against is wrong")
                        self.format_err_count["evidence against"] += 1
                    if len(q) == 8 and '\"deliberation\"' not in line:
                        something_wrong = True
                        print("deliberation is wrong")
                        self.format_err_count["deliberation"] += 1
                    if len(q) == 9 and '\"verdict\"' not in line:
                        something_wrong = True
                        print("verdict is wrong")
                        self.format_err_count["verdict"] += 1


                    if something_wrong:
                        print("Found format following error in LLM output!!")
                        key_log_lines_line = None
                        ts_line = None
                        pid_line = None
                        evidencefor_line = None
                        evidenceagainst_line = None
                        deliberation_line = None
                        verdict_line = None
                        exfiltrated_data_line = None
                        exfiltration_method_line = None

                        poplast = False
                        while q:
                            if poplast == False:
                                q.popleft()
                                poplast = True
                            if len(q) == 9 and poplast:
                                verdict_line = q.popleft()
                            if len(q) == 8 and poplast:
                                deliberation_line = q.popleft()
                            if len(q) == 7 and poplast:
                                evidenceagainst_line = q.popleft()
                            if len(q) == 6 and poplast:
                                evidencefor_line = q.popleft()
                            if len(q) == 5 and poplast:
                                exfiltrated_data_line = q.popleft()
                            if len(q) == 4 and poplast:
                                exfiltration_method_line = q.popleft()
                            if len(q) == 3 and poplast:
                                pid_line = q.popleft()
                            if len(q) == 2 and poplast:
                                ts_line = q.popleft()
                            if len(q) == 1 and poplast:
                                key_log_lines_line = q.popleft()

                        gtfriendly_timestamp, exfiltrated_data, pid, exfiltration_method, key_log_lines, evidencefor, evidenceagainst, deliberation, verdict = self.process_llm_exfiltration_outputs(ts_line, exfiltrated_data_line, pid_line, exfiltration_method_line, key_log_lines_line, evidencefor_line, evidenceagainst_line, deliberation_line, verdict_line)

                        if gtfriendly_timestamp != None and exfiltrated_data != None:
                            llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, exfiltrated_data, pid, exfiltration_method, key_log_lines, evidencefor, evidenceagainst, deliberation, verdict)))

                    something_wrong = False

                if len(q) == 9:
                    key_log_lines_line = q.pop()
                    ts_line = q.pop()
                    pid_line = q.pop()
                    exfiltration_method_line = q.pop()
                    exfiltrated_data_line = q.pop()
                    evidencefor_line = q.pop()
                    evidenceagainst_line = q.pop()
                    deliberation_line = q.pop()
                    verdict_line = q.pop()

                    assert len(q) == 0, print("Did not completely empty the queue")

                    gtfriendly_timestamp, exfiltrated_data, pid, exfiltration_method, key_log_lines, evidencefor, evidenceagainst, deliberation, verdict = self.process_llm_exfiltration_outputs(ts_line, exfiltrated_data_line, pid_line, exfiltration_method_line, key_log_lines_line, evidencefor_line, evidenceagainst_line, deliberation_line, verdict_line)

                    # llmresponse_dict[k].append(tuple((jsonobjectcnt_per_chunk[k], timestamp, external_host, method, username, evidence)))
                    llmresponse_dict[llmoutput_chunk_key][current_rdnum].append(tuple((current_rdnum, gtfriendly_timestamp, exfiltrated_data, pid, exfiltration_method, key_log_lines, evidencefor, evidenceagainst, deliberation, verdict)))

        for k,v in jsonobjectcnt_per_chunk.items():
            num_rounds = max(num_rounds, v)
        
        return llmresponse_dict, num_rounds